spring.application.name=invoiceflow-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/invoiceflow_db
spring.datasource.username=postgres
spring.datasource.password=Mikele987@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=questa-chiave-deve-essere-lunga-almeno-32-caratteri-super-segreta
jwt.expiration=86400000
